# ArenaFighter Configuration
# To configure your arenas, run /arena create <arena_name> in game
# then you can modify it in arenas.properties in the ArenaFighter folder

#Combat logging punishment
punishment:
  duration-minutes: 5

#Command blocking for players during a fight
blocked-commands:
  - "/spectate"
  - "/spawn"
  - "/home"
  - "/homes"
  - "/sethome"
  - "/warp"
  - "/tp"
  - "/tpa"
  - "/tpaccept"
  - "/tphere"
  - "/heal"
