# ArenaFighter Configuration
# To configure your arenas, run /arena create <arena_name> in game
# then you can modify it in arenas.properties in the ArenaFighter folder

#Combat logging punishment
punishment:
  duration-minutes: 5
