# ArenaFighter Configuration
# This file contains the configuration for arena locations

# Example arena configuration
# You can add multiple arenas by copying this structure or running /arena create <name> in game to automatically generate a config
# Spawn 1 and 2 correspond to separate player spawns in the arena, spectatorSpawn corresponds to the spawn spectators go to when viewing a match (preferably seperated from the arena)
arenas:
  example_arena:
    world: world
    spawn1:
      x: 100.5
      y: 64.0
      z: 200.5
      yaw: 0.0
      pitch: 0.0
    spawn2:
      x: 120.5
      y: 64.0
      z: 200.5
      yaw: 180.0
      pitch: 0.0
    spectatorSpawn:
      x: 110.5
      y: 64.0
      z: 200.5
      yaw: 0
      pitch: 0.0

#Combat logging punishment
punishment:
  duration-minutes: 5
